"""Coding-Agent Wrapper and CLI Delegation Interface.

Task 2.1: CodingAgent — wraps external coding CLIs (Claude Code, Codex,
OpenCode) to generate skills following TDD methodology with method-skill
prompt templates and quality gates.

Task 2.2: CLIDelegator — routes task types (feature/fix/refactor) to the
appropriate coding CLI with fallback support.
"""

from __future__ import annotations

import ast
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------


@dataclass
class SkillSpec:
    """Specification for a skill to be generated by the coding agent."""

    name: str
    description: str
    signature: str
    test_cases: list[str] = field(default_factory=list)


@dataclass
class CodingResult:
    """Result returned by CodingAgent.create_skill."""

    code: str
    tests: str
    success: bool
    error: str = ""
    cli_used: str = ""


@dataclass
class QualityResult:
    """Quality-gate results for generated code."""

    ruff_passed: bool
    mypy_passed: bool
    ast_valid: bool
    issues: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# CLI Delegation configs (Task 2.2 — declared early so both classes share them)
# ---------------------------------------------------------------------------


DEFAULT_CLI_CONFIGS: dict = {
    "claude": {"command": "claude", "args": ["--print"], "timeout": 300},
    "codex": {"command": "codex", "args": [], "timeout": 300},
    "opencode": {"command": "opencode", "args": [], "timeout": 300},
    "aider": {"command": "aider", "args": ["--no-auto-commits", "--yes"], "timeout": 300},
}

TASK_CLI_MAP: dict = {
    "feature": ["claude", "codex", "opencode", "aider"],
    "fix": ["codex", "claude", "opencode", "aider"],
    "refactor": ["opencode", "claude", "codex", "aider"],
}


def _cli_available(cli_name: str) -> bool:
    """Check whether a CLI binary is available on PATH."""
    config = DEFAULT_CLI_CONFIGS.get(cli_name, {"command": cli_name})
    return shutil.which(config["command"]) is not None


def ensure_coding_cli() -> str:
    """Ensure at least one coding CLI is available.

    Checks claude, codex, opencode, aider in order. If none is found,
    installs aider-chat via ``uv add aider-chat`` and returns "aider".
    Returns the name of the first available CLI.

    Raises RuntimeError if the installation fails.
    """
    for cli_name in ["claude", "codex", "opencode", "aider"]:
        if _cli_available(cli_name):
            return cli_name

    # No CLI found — install aider-chat as fallback
    proc = subprocess.run(
        ["uv", "add", "aider-chat"],
        capture_output=True,
        text=True,
        timeout=120,
        check=False,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"No coding CLI found and aider-chat installation failed "
            f"(exit code {proc.returncode}): {proc.stderr or proc.stdout}"
        )
    return "aider"


# ---------------------------------------------------------------------------
# CodingAgent (Task 2.1)
# ---------------------------------------------------------------------------


class CodingAgent:
    """Wraps external coding CLIs to generate skills via TDD methodology.

    Uses method-skill prompt templates (writing-plans, TDD, debugging,
    code-review) to structure the code generation process and runs quality
    gates (ruff, mypy, AST validation) on the output.
    """

    def __init__(
        self,
        cli_primary: str = "",
        cli_fallbacks: list[str] | None = None,
        timeout: int = 300,
    ) -> None:
        # Auto-detect available CLI; install aider-chat if none found
        if not cli_primary:
            cli_primary = ensure_coding_cli()
        self.cli_primary = cli_primary
        self.cli_fallbacks = cli_fallbacks if cli_fallbacks is not None else [
            "codex",
            "opencode",
            "aider",
        ]
        self.timeout = timeout

    # -- public API ---------------------------------------------------------

    def revise_code(self, code: str, error_trace: str, spec: SkillSpec) -> str | None:
        """Ask the coding agent to revise *code* based on *error_trace*.

        Returns the revised code string, or ``None`` if the CLI produced no
        usable output.
        """
        debug_prompt = self._debugging_prompt(error_trace)
        full_prompt = (
            f"{debug_prompt}\n\n"
            f"## Current Code\n```python\n{code}\n```\n\n"
            f"## Skill Spec\n"
            f"Name: {spec.name}\n"
            f"Description: {spec.description}\n"
            f"Signature: {spec.signature}\n\n"
            "Output ONLY the corrected Python code, no explanations.\n"
        )
        try:
            revised = self._call_cli(full_prompt, self.cli_primary)
        except Exception:
            return None
        if revised and revised.strip():
            return revised
        return None

    def create_skill(self, spec: SkillSpec) -> CodingResult:
        """Generate code + tests for *spec* using TDD methodology.

        Flow:
          1. Build a writing-plans prompt (implementation steps).
          2. Build a TDD prompt (tests first).
          3. Call the CLI to generate code, falling back through
             ``cli_fallbacks`` if the primary CLI fails.
          4. Run quality gates on the result.
        """
        plan_prompt = self._writing_plans_prompt(spec)
        tdd_prompt = self._tdd_prompt(spec)
        full_prompt = f"{plan_prompt}\n\n{tdd_prompt}"

        ordered_clis = [self.cli_primary] + list(self.cli_fallbacks)
        cli_used = ""
        code = ""
        last_error = ""

        for cli_name in ordered_clis:
            try:
                raw = self._call_cli(full_prompt, cli_name)
            except subprocess.TimeoutExpired as exc:
                last_error = f"CLI '{cli_name}' timed out: {exc}"
                continue
            except Exception as exc:  # pragma: no cover - defensive
                last_error = f"CLI '{cli_name}' error: {exc}"
                continue

            if not raw.strip():
                last_error = f"CLI '{cli_name}' produced empty output"
                continue

            code = raw
            cli_used = cli_name
            break

        if not code:
            return CodingResult(
                code="",
                tests="",
                success=False,
                error=last_error or "All CLIs failed to produce output",
                cli_used="",
            )

        # Generate tests via TDD prompt
        tests = ""
        try:
            tests = self._call_cli(tdd_prompt, cli_used)
        except Exception:
            tests = ""

        # Quality gates
        quality = self._run_quality_gates(code)
        if not quality.ast_valid:
            return CodingResult(
                code=code,
                tests=tests,
                success=False,
                error=f"AST validation failed: {quality.issues}",
                cli_used=cli_used,
            )

        return CodingResult(
            code=code,
            tests=tests,
            success=True,
            error="",
            cli_used=cli_used,
        )

    # -- prompt templates ---------------------------------------------------

    def _writing_plans_prompt(self, spec: SkillSpec) -> str:
        """Break the skill spec into bite-sized implementation steps."""
        test_lines = "\n".join(f"  - {t}" for t in spec.test_cases) or "  (none)"
        return (
            f"# Implementation Plan for skill '{spec.name}'\n\n"
            f"## Description\n{spec.description}\n\n"
            f"## Signature\n{spec.signature}\n\n"
            f"## Test Cases\n{test_lines}\n\n"
            "Break this into bite-sized, sequential implementation steps.\n"
            "For each step, describe the exact file path, function, and code.\n"
            "Keep each step small and independently verifiable.\n"
        )

    def _tdd_prompt(self, spec: SkillSpec) -> str:
        """Generate test-first instructions (RED → GREEN → REFACTOR)."""
        test_lines = "\n".join(f"  - {t}" for t in spec.test_cases) or "  (derive from signature)"
        return (
            f"# TDD Instructions for skill '{spec.name}'\n\n"
            f"Follow strict test-first methodology:\n"
            f"1. RED   — write failing tests first\n"
            f"2. GREEN — write minimal code to pass tests\n"
            f"3. REFACTOR — improve code while tests stay green\n\n"
            f"## Signature\n{spec.signature}\n\n"
            f"## Tests to write first\n{test_lines}\n\n"
            "Output the test code first, then the implementation code.\n"
        )

    def _debugging_prompt(self, error_trace: str) -> str:
        """4-phase root cause analysis prompt."""
        return (
            "# Debugging — 4-Phase Root Cause Analysis\n\n"
            f"## Error Trace\n{error_trace}\n\n"
            "Follow these phases:\n"
            "1. UNDERSTAND — reproduce and read the error carefully\n"
            "2. ISOLATE    — narrow down to the smallest failing case\n"
            "3. FIX        — apply the minimal correct fix\n"
            "4. VERIFY     — confirm the fix resolves the root cause\n"
        )

    def _code_review_prompt(self, code: str) -> str:
        """Pre-commit review checklist prompt."""
        return (
            "# Pre-Commit Code Review Checklist\n\n"
            "Review the following code against this checklist:\n"
            "- Correctness: does it do what the signature claims?\n"
            "- Security: any injection / unsafe operations?\n"
            "- Style: PEP-8, naming, docstrings?\n"
            "- Tests: are edge cases covered?\n"
            "- Performance: obvious bottlenecks?\n\n"
            f"## Code\n```\n{code}\n```\n"
        )

    # -- quality gates ------------------------------------------------------

    def _run_quality_gates(self, code: str) -> QualityResult:
        """Run ruff, mypy, and AST validation on *code*."""
        issues: list[str] = []

        # AST validation — always runs, deterministic
        ast_valid = True
        try:
            ast.parse(code)
        except SyntaxError as exc:
            ast_valid = False
            issues.append(f"ast: SyntaxError line {exc.lineno}: {exc.msg}")

        # ruff check — runs if ruff is available
        ruff_passed = True
        ruff_path = shutil.which("ruff")
        if ruff_path:
            try:
                proc = subprocess.run(
                    ["ruff", "check", "--stdin-filename", "generated.py", "-"],
                    input=code,
                    capture_output=True,
                    text=True,
                    timeout=30,
                )
                if proc.returncode != 0:
                    ruff_passed = False
                    issues.append(f"ruff: {proc.stdout.strip() or proc.stderr.strip()}")
            except Exception as exc:
                ruff_passed = False
                issues.append(f"ruff: {exc}")
        # If ruff isn't installed we treat it as passed (not a hard failure).

        # mypy check — runs if mypy is available
        mypy_passed = True
        mypy_path = shutil.which("mypy")
        if mypy_path:
            try:
                proc = subprocess.run(
                    ["mypy", "-c", code],
                    capture_output=True,
                    text=True,
                    timeout=30,
                )
                if proc.returncode != 0:
                    mypy_passed = False
                    issues.append(f"mypy: {proc.stdout.strip() or proc.stderr.strip()}")
            except Exception as exc:
                mypy_passed = False
                issues.append(f"mypy: {exc}")
        # If mypy isn't installed we treat it as passed (not a hard failure).

        return QualityResult(
            ruff_passed=ruff_passed,
            mypy_passed=mypy_passed,
            ast_valid=ast_valid,
            issues=issues,
        )

    # -- CLI invocation -----------------------------------------------------

    def _call_cli(self, prompt: str, cli_name: str) -> str:
        """Call *cli_name* via subprocess, returning its stdout.

        For aider, the project's AGENTS.md is passed as a read-only file
        so the coding agent follows the project's operational rules.

        Raises ``subprocess.TimeoutExpired`` on timeout so callers can
        fall back to the next CLI.
        """
        config = DEFAULT_CLI_CONFIGS.get(cli_name, {"command": cli_name, "args": [], "timeout": self.timeout})
        command = [config["command"]] + list(config.get("args", []))
        timeout = config.get("timeout", self.timeout)

        # Aider: pass AGENTS.md as context file
        if cli_name == "aider":
            agents_md = self._find_agents_md()
            if agents_md:
                command += ["--read", str(agents_md)]

        proc = subprocess.run(
            command,
            input=prompt,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        if proc.returncode != 0:
            raise RuntimeError(
                f"CLI '{cli_name}' exited with code {proc.returncode}: "
                f"{proc.stderr or proc.stdout or '<no output>'}"
            )
        if not proc.stdout.strip():
            raise ValueError(f"CLI '{cli_name}' produced empty output")
        return proc.stdout

    @staticmethod
    def _find_agents_md() -> Path | None:
        """Locate AGENTS.md in the project root (cwd or parent of src/)."""
        candidates = [
            Path.cwd() / "AGENTS.md",
            Path.cwd().parent / "AGENTS.md",
            Path(__file__).resolve().parent.parent.parent / "AGENTS.md",
        ]
        for c in candidates:
            if c.is_file():
                return c
        return None


# ---------------------------------------------------------------------------
# CLIDelegator (Task 2.2)
# ---------------------------------------------------------------------------


class CLIDelegator:
    """Routes task types (feature/fix/refactor) to coding CLIs with fallback.

    Uses ``TASK_CLI_MAP`` to pick the primary CLI for each task type, then
    falls back through the remaining CLIs if the primary fails.
    """

    def __init__(self, cli_configs: dict | None = None) -> None:
        self.cli_configs = cli_configs if cli_configs is not None else dict(DEFAULT_CLI_CONFIGS)

    def delegate(self, task_type: str, prompt: str) -> str:
        """Delegate *prompt* to the appropriate CLI for *task_type*.

        Falls back through the CLI list if the primary CLI fails.
        Returns the output text, or an error string if all CLIs fail.
        """
        cli_list = TASK_CLI_MAP.get(task_type, TASK_CLI_MAP.get("feature"))
        if cli_list is None:
            cli_list = TASK_CLI_MAP.get("feature", ["claude"])
        for cli_name in cli_list:
            output, success = self._try_cli(cli_name, prompt)
            if success:
                return output
        return f"Error: all CLIs failed for task_type '{task_type}'"

    def _select_cli(self, task_type: str) -> str:
        """Map a task type to its primary CLI name."""
        cli_list = TASK_CLI_MAP.get(task_type)
        if not cli_list:
            raise ValueError(f"Unknown task_type: {task_type!r}")
        return cli_list[0]

    def _try_cli(self, cli_name: str, prompt: str) -> tuple:
        """Try one CLI, returning (output, success)."""
        config = self.cli_configs.get(cli_name)
        if config is None:
            return (f"Unknown CLI: {cli_name}", False)

        command = [config["command"]] + list(config.get("args", []))
        timeout = config.get("timeout", 300)

        try:
            proc = subprocess.run(
                command,
                input=prompt,
                capture_output=True,
                text=True,
                timeout=timeout,
            )
        except subprocess.TimeoutExpired:
            return (f"CLI '{cli_name}' timed out", False)
        except FileNotFoundError:
            return (f"CLI '{cli_name}' not found", False)
        except Exception as exc:  # pragma: no cover - defensive
            return (f"CLI '{cli_name}' error: {exc}", False)

        if proc.returncode == 0 and proc.stdout.strip():
            return (proc.stdout, True)
        return (proc.stderr or proc.stdout or f"CLI '{cli_name}' produced no output", False)